version: "3.8"

networks:
  order:
    driver: bridge

services:

  order:
    image: "order-service"
    container_name: "order"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      - SERVER_PORT=9001
      - BPL_JVM_THREAD_COUNT=50
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
    networks:
      - order