version: "3"
services:
  kafka-streams-quarkus:
    build: kafka-streams-quarkus
    restart: unless-stopped
    container_name: kafka-streams-quarkus
    environment:
      - QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS=kafka:9092
      - ORDERS_TOPIC=orders
      - PRODUCTS_TOPIC=mysql.pizzashop.products
      - ENRICHED_ORDER_ITEMS_TOPIC=enriched-order-items
      - ENRICHED_ORDERS_TOPIC=enriched-orders
      - PINOT_BROKER=pinot-broker:8099
    depends_on:
      - kafka
    networks:
      - rta
    ports:
      - "8080:8080"
networks:
  rta:
    name: rta